version: 1
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.2

    working_directory: ~/app
    steps:
      # git pull
      - checkout
      - run:
          name: Setting up Docker
          command: |
           echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
           docker run -d --name db company/proprietary-db:1.2.3


      # Download and cache dependencies
      - restore_cache:
          keys:
            - app-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: app-{{ checksum "pom.xml" }}

      # package into a jar
      - run:
          name: Packaging
          command : mvn clean package

      - run:
          name: Push app to DockerHub
          command: |
            docker build --tag=aliyura/demo-ci:latest .
            docker push aliyura/demo-ci:latest

      - run:
          name: Deployment
          command: |
            ssh $SERVER_HOST
            sudo docker pull aliyura/demo-ci:latest