version: 1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-stretch
        
    working_directory: ~/app

    steps:
      # git pull
      - checkout
      - add_ssh_keys:
          fingerprints:
            - $FINGERPRINT

      # setup testing env
      # the following commented lines are not allowed in the free version of circleci
      #       - setup_remote_docker:
      #           docker_layer_caching: true
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # Download and cache dependencies
      - restore_cache:
          keys:
            - app-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: app-{{ checksum "pom.xml" }}

      # package into a jar
      - run:
          name: Packaging
          command : mvn clean package

      - run:
          name: Push app to DockerHub
          command: docker build --tag=aliyura/demo-ci:latest .
                   docker push aliyura/demo-ci:latest

      - run:
          name: Deployment
          command: ssh $SERVER_HOST
                   sudo docker pull aliyura/demo-ci:latest